### ISSUE TITLE
Error message when the game start

### ISSUE THREAD

**Issue by rlepigre** [phyver/GameShell#48]
There is a weird error message printed at the start of the game.
```
/home/rodolphe/dev/GameShell/bin/_gsh_pcm: line 10: return: can only `return' from a function or sourced script

  |                                                   |
--+---------------------------------------------------+--
  | Run the command                                   |
  |     $ gsh goal                                    |
  | to discover your first mission.                   |
  |                                                   |
  | You can check the mission has been completed with |
  |     $ gsh check                                   |
  |                                                   |
  | The command                                       |
  |     $ gsh help                                    |
  | displays the list of available (gsh) commands.    |
--+---------------------------------------------------+--
  |                                                   |

[mission 1] $ 
```

**Comment by phyver** [comment]
I've already seen this bug, but not for this file.
Apparently, `bash` will complain, but debian's `sh` won't.
Is your `sh` a link to `bash`? (That would start it in POSIX mode...)

**Comment by rlepigre** [comment]
> Is your `sh` a link to `bash`? (That would start it in POSIX mode...)

Yes, it is indeed a link to `bash` on my system.

**Comment by phyver** [comment]
Is that fixed now?

**Comment by rlepigre** [comment]
No, that is not fixed, at least with 2f4ee13395949da1a4c86185118289aa99183602.

**Comment by phyver** [comment]
And with 81852cc ?

**Comment by rlepigre** [comment]
Yes, no more message!

**Comment by phyver** [comment]
And I thought testing with `dash` would catch more bugs than with `bash` in POSIX mode!
